{
  "containers": {
    "cna": {
      "providerMetadata": {
        "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09"
      },
      "title": "FTP_TLS instance with unverified SSL context",
      "problemTypes": [
        {
          "descriptions": [
            {
              "description": "CWE-295 Improper Certificate Validation",
              "lang": "en",
              "cweId": "CWE-295",
              "type": "CWE"
            }
          ]
        }
      ],
      "source": {
        "discovery": "UNKNOWN"
      },
      "affected": [
        {
          "vendor": "Apache Software Foundation",
          "product": "Apache Airflow FTP Provider",
          "collectionURL": "https://pypi.python.org",
          "packageName": "apache-airflow-providers-ftp",
          "versions": [
            {
              "status": "affected",
              "version": "0",
              "lessThan": "3.7.0",
              "versionType": "semver"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "descriptions": [
        {
          "value": "Improper Certificate Validation vulnerability in Apache Airflow FTP Provider.\n\nThe FTP hook lacks complete certificate validation in FTP_TLS connections, which can potentially be leveraged. Implementing proper certificate validation by passing context=ssl.create_default_context() during FTP_TLS instantiation is used as mitigation to validate the certificates properly.\n\nThis issue affects Apache Airflow FTP Provider: before 3.7.0.\n\nUsers are recommended to upgrade to version 3.7.0, which fixes the issue.\n\n",
          "lang": "en",
          "supportingMedia": [
            {
              "type": "text/html",
              "base64": false,
              "value": "Improper Certificate Validation vulnerability in Apache Airflow FTP Provider.<br><br><p>The FTP hook lacks complete certificate validation in FTP_TLS connections, which can potentially be leveraged. Implementing proper certificate validation by passing context=ssl.create_default_context() during FTP_TLS instantiation is used as mitigation to validate the certificates properly.</p><p><span style=\"background-color: var(--wht);\">This issue affects Apache Airflow FTP Provider: before 3.7.0.</span><br></p><p>Users are recommended to upgrade to version 3.7.0, which fixes the issue.</p>"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/apache/airflow/pull/38266",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/apache/airflow/blob/95e26118b828c364755f3a8c96870f3591b01c31/airflow/providers/ftp/hooks/ftp.py#L280",
          "tags": [
            "technical-description"
          ]
        },
        {
          "url": "https://docs.python.org/3/library/ssl.html#best-defaults",
          "tags": [
            "technical-description"
          ]
        },
        {
          "url": "https://lists.apache.org/thread/265t5zbmtjs6h9fkw52wtp03nsbplky2",
          "tags": [
            "vendor-advisory"
          ]
        }
      ],
      "metrics": [
        {
          "other": {
            "type": "Textual description of severity",
            "content": {
              "text": "low"
            }
          }
        }
      ],
      "credits": [
        {
          "lang": "en",
          "value": "Eric Brown of Secure Sauce LLC",
          "type": "finder"
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.1.0-dev"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-29733",
    "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
    "serial": 1,
    "state": "PUBLISHED"
  },
  "dataType": "CVE_RECORD",
  "dataVersion": "5.0"
}